/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Adder__ */

#ifndef _Included_Adder__
#define _Included_Adder__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Adder__
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Adder_00024_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
