/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MatMul__ */

#ifndef _Included_MatMul__
#define _Included_MatMul__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MatMul__
 * Method:    matmul
 * Signature: ([[I[[I[[I)V
 */
JNIEXPORT void JNICALL Java_MatMul_00024_matmul
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
